version: '3'
services:

    reverse-proxy:
        image: apache
        build:
            context: ./reverse-proxy/
        ports:
          - 80:80

    blog-frontend:
        image: blog-frontend
        build:
            context: ./soasec-blog/
        restart: always
    
    blog-frontend-area_riservata:
        image: blog-frontend-area_riservata
        build:
            context: ./soasec-blog-area_riservata/
        restart: always

    mongo_auth:
        image: mongo
        restart: always
        volumes:
            - auth-db:/data/db
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: test

    auth:
        image: blog-auth
        volumes:
            - auth-uploads:/app/public/uploads
        build:
            context: ./auth-server
        restart: always
        environment:
            DB_HOST: ${AUTH_DB_HOST-mongo_auth}
            DB_PORT: ${AUTH_DB_PORT-27017}

    mongo_api:
        image: mongo
        restart: always
        volumes:
            - api-db:/data/db
        ports:
            - 27018:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: test

    api:
        image: blog-api
        volumes:
            - api-uploads:/app/public/uploads
        build:
            context: ./soasec-blog-backend
        restart: always
        environment:
            DB_HOST: ${API_DB_HOST-mongo_api}
            DB_PORT: ${API_DB_PORT-27017}
volumes:
    auth-db:
    auth-uploads:
    api-db:
    api-uploads: