name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker images
      run: |
       docker build ./soasec-blog --tag ghcr.io/alexhx12/soasec-blog-frontend:latest
       docker push ghcr.io/alexhx12/soasec-blog-frontend:latest
       docker build ./auth-server --tag ghcr.io/alexhx12/soasec-auth-server:latest
       docker push ghcr.io/alexhx12/soasec-auth-server:latest
       docker build ./soasec-blog-backend --tag ghcr.io/alexhx12/soasec-blog-api:latest
       docker push ghcr.io/alexhx12/soasec-blog-api:latest